name: Container Build
description: Builds a container image
author: https://github.com/theopenlane
requirements:
  - docker
configuration:
  properties:
    dockerfile:
      type: string
      description: The path to the Dockerfile
      default: Dockerfile
    context:
      type: string
      description: The path to the context directory
      default: .
    secret-file:
      type: string
      description: A string like 'id=mysecret,src=secret-file' where <secret-file> is the path in the build
    tags:
      type: array
      description: A list of tags to build
    labels:
      type: array
      description: A list of labels to build
    build-args:
      type: array
      description: A list of build arguments to pass to the Dockerfile
    push:
      type: boolean
      description: Whether to push the image to the registry
      default: false
    platforms: 
      type: string
      description: a comma separated string of platforms to build for
  additionalProperties: false
