version: "3"

tasks:
  install:
    desc: install packages required for working with this repo
    cmds:
      - brew install shellcheck

  shellcheck:
    desc: shellcheck
    cmds:
      - shellcheck hooks/** scripts/**

  lint:
    desc: runs the buildkite compose linter
    cmds:
      - docker compose run --rm lint

  test:
    desc: runs the buildkite plugin tester
    cmds:
      - docker compose run --rm tests

  ci:
    desc: runs all the commands that will be run in CI
    cmds:
      - task: shellcheck
      - task: lint
      - task: test

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files
