steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.4.0:
        files:
          - hooks/**
          - scripts/**

  - label: ":rocket: Test"
    plugins:
      docker-compose#v5.4.0:
        run: tests
        cli-version: 2

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.3.0:
        id: theopenlane/container-build
